# name of the software
name: strman
# current version of the software
version: 1.0.3
# url of the download button
downloadUrl: https://github.com/dleitee/strman
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/dleitee/strman

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/dleitee/strman
  - title: Issues
    url: https://github.com/dleitee/strman/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: dleitee
  repo: strman

# twitter buttons
twitter:
  enabled: true
  via: dleitee
  hash: strman nodejs javascript
  account: dleitee

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
